baseURL = "https://resources.cfaz.dev/"
languageCode = "en-us"
title = "CFaz gamedev resources"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

pluralizelisttitles = false

[params]
  author = "CFaz gamedev resources"
  message = "A collaborative list of resources for game development."
  hideAutoMenu = false

[[menu.main]]
name = "Contribute"
url = "/contribute"
weight = 1

[[menu.main]]
name = "Contact"
url = "https://cfaz.dev"
weight = 0

#[social]
#  facebook = "https://facebook.com"
#  twitter = "https://twitter.com"
#  instagram = "https://instagram.com"
#  linkedin = "https://linkedin.com"